### ISSUE TITLE
setting pauseOnBlur to true does not stop the audio on blur

### ISSUE THREAD

**Issue by klaritan** [phaserjs/phaser#6354] opened 2023-01-19 22:45 UTC
## Version

* Phaser Version: 3.60 beta18

* Operating system: Windows 10

* Browser: Firefox

## Description

setting pauseOnBlur to true does not stop the audio on blur

**Comment by photonstorm** [comment] 2023-01-20 16:38
Tested, and of course, because it's Firefox, this doesn't work now. Still works fine on Chrome and Edge. Typical.

**Comment by klaritan** [comment] 2023-01-21 03:21
> Tested, and of course, because it's Firefox, this doesn't work now. Still works fine on Chrome and Edge. Typical.

Are you sure? Audio keeps playing even on Android WebView when the app is switched or otherwise minimized. The app also sends proper "onPause" events to the WebView.

**Comment by samme** [comment] 2023-02-10 23:27
I think this is caused by https://github.com/photonstorm/phaser/commit/320317c884a26589f4485c67c4c9033e4bbac059

Firefox is suspending the audio context but then resuming it again from `Phaser.Sound.WebAudioSoundManager#update()`.

**Comment by SlimHajRomdhane** [comment] 2023-03-25 11:24
One possible workaround for this issue is to manually pause the audio context when the game loses focus. This can be done using the window.onblur event and the pauseAll method of the sound manager. For example:

this.sound.pauseAll();

window.onblur = function() {
    this.sound.pauseAll();
};

This should ensure that audio is paused when the game loses focus, regardless of whether the pauseOnBlur property is being respected by the browser.

I hope this helps!
- SlimHR

**Comment by michalfialadev** [comment] 2023-03-28 10:08
Adding few more tests for diff. OSes/devices from our QA team in regards to this (same audio handling worked ok in all following cases running app version w/ Phaser 3.24.1).

Following are tests done on game version running Phaser 3.60b20:

Testcase # 1 – iPhone 12 (iOS 16):
Launch game in browser (Safari), make sure game's music is playing
Switch to another browser tab
==> Notice game's music keeps playing – NOT OK – should get muted (and resume once player returns to game)

Testcase # 2 – iPhone 12 (iOS 16):
Launch game in browser (Safari), make sure game's music is playing
Send Safari app to background and use another app
==> Notice game's music is muted – OK

Testcase # 3 – Google Pixel 6 (Android 13):
Launch game in browser (Chrome), make sure game's music is playing
Switch to another browser tab
==> Notice game's music keeps playing – NOT OK – should get muted (and resume once player returns to game)

Testcase # 4 – Google Pixel 6 (Android 13):
Launch game in browser (Chrome), make sure game's music is playing
Send Chrome app to background and use another app
==> Notice game's music keeps playing (with a short "hiccup") – NOT OK – should get muted (and resume once player returns to game)

Testcase # 5 – Safari on macOS:
Launch game in browser, make sure game's music is playing
Switch to another browser tab
==> Notice game's music is muted – OK

Testcase # 6 – Safari on macOS:
Launch game in browser, make sure game's music is playing
Use another app in foreground, so browser is not the foreground app.
==> Notice game's music keeps playing (with a "hiccup") —> actually it's not so bad on Desktop, some other websites/games do this as well.
However for sure it'd be more consistent (also easier to implement?) if music always mutes on all platforms whenever game's browser window/tab is not the front-most process.

Behavior on Chrome (macOS) is exactly the same as Safari (macOS) above.
Firefox (macOS) is similar also, however switching to another tab does NOT mute music as well.

**Comment by photonstorm** [comment] 2023-04-12 02:23
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed as completed** 2023-04-12 02:23 UTC
Labels: 🐛 Browser Bug, 🎵 Audio
