### ISSUE TITLE
Particles flickering on iOS with Phaser 3.60.0

### ISSUE THREAD

**Issue by mattkelliher** [phaserjs/phaser#6483] opened 2023-04-19 20:41 UTC
## Version
* Phaser Version: 3.60.0
* Operating system: iOS 16
* Browser: Tested on mobile Safari and Firefox Focus

## Description
Particles seem to flicker and pass through each other with the new Particle Emitter system. This only appears to happen on mobile, and is working fine on MacOS.

## Example Test Code

See Phaser particle emitter examples, e.g. [Custom Callback](https://labs.phaser.io/view.html?src=src\game%20objects\particle%20emitter\custom%20callback.js). 

## Additional Information

The particles seem to render just fine in screenshots, and when trying to take a video when holding the phone up to a laptop camera, which makes things a bit difficult.

**Comment by spayton** [comment] 2023-05-26 16:56
I also get this.  It also does it by setting the device to an iphone in dev tools. It looks like flickering on overlapped particles, but only on the overlap.

In my app, on iphone, generate a view with overlapping particels and freeze it by setting timeScale = 0 to see exactly whats going on.

Seems easy to reproduce on examples too.  On win10 desktop chrome browser, visit above 'custom callback' link, go into dev tools and select iphone device and refresh.

**Comment by spayton** [comment] 2023-06-19 21:13
Todays chat on discord revealed the fix, setting stableSort in the config to true fixed it for me.

**Comment by photonstorm** [comment] 2023-09-07 15:22
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed as completed** 2023-09-07 15:22 UTC
Labels: 🦔 Need to reproduce, ✨ Particles
