### ISSUE TITLE
`createFromObjects()` doesn't copy custom properties

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6391] opened 2023-02-17 02:44 UTC
## Version

* Phaser Version: 3.60.0-beta.18

## Description

> For example giving an Object a property of `alpha: 0.5` in Tiled will be reflected in the Game Object that is created.

This happened in v3.55.2 but it doesn't happen now. 

## Example Test Code

<https://labs.phaser.io/edit.html?src=src/3.60\tilemap\create%20from%20objects.js&v=3.60.0-beta.18>

```js
const coinObject = this.map.objects[0].objects[3];

console.assert(coinObject.properties.alpha === 0.25);

const [ coin ] = this.map.createFromObjects('Coin Object Layer', [
    { id: coinObject.id, key: 'coin' }
]);

console.assert(coin.alpha === 0.25, 'Coin sprite should have alpha 0.25 not %s', coin.alpha);
```

**Comment by photonstorm** [comment] 2023-03-22 16:41
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed as completed** 2023-03-22 16:41 UTC
Labels: 🗺️ Tilemap

**Comment by paxperscientiam** [comment] 2023-04-25 02:18
@photonstorm I guess the currently documented behavior is changing, then? Per [new docs](https://newdocs.phaser.io/docs/3.60.0/Phaser.Tilemaps.Tilemap#createFromObjects), "Custom object properties that do not exist as a Game Object property are set in the Game Objects [data](https://newdocs.phaser.io/docs/3.60.0/Phaser.GameObjects.GameObject#data)."

That said, an option to automatically update gameobject properties based on custom properties sounds great.

**Comment by samme** [comment] 2023-04-25 13:41
The correct behavior should be the same in v3.55 and v3.60. The incorrect behavior was in the some of the v3.60 betas only.

If you create a sprite from Tiled Object

    { alpha: 0.5, color: 'green' }

then the resulting sprite will have

    alpha === 0.5
    data.values.color === 'green'

Here `color` is the custom object property.

**Comment by paxperscientiam** [comment] 2023-04-26 06:47
Thanks for underscoring that, @samme . I definitely misread it.

That said, I cannot get custom properties to have any effect. In my case, I'm creating game objects from a class that extends `Physics.Matter.Image` in this way:

```ts
        this.tileMap.createFromObjects("GameObjects/Ships", {
            name: "SimpleShip",
            scene: this,
            key: "ship",
            classType: SimpleShip,
        })
```

The corresponding "SimpleShip" entry in Tiled on the Tiled layer "GameObjects/Ships" is defined like this:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/7539871/234489096-dbf94b39-dd10-41dc-9474-5fe7930347f9.png">


This works great, except for the custom properties issue.

Examining the data store ...
<img width="290" alt="image" src="https://user-images.githubusercontent.com/7539871/234490283-2e19a276-b255-4c80-a9df-fd08f37026e9.png">

Only "alpha" and "color" show up. Alpha shouldn't even be there, if I understand you correctly. "dummy" should be there, but it's not.

`gameObject.alpha`, `gameObject.flipX`, and `gameObject.flipY` are the default values (1, false, false).

For completeness, I tried again without a custom class (I added to the aforementioned Tiled Layer an object named "LOL").

```ts
        const LOL = this.tileMap.createFromObjects("GameObjects/Ships", {
            name: "LOL",
            scene: this
        })
```
<img width="247" alt="image" src="https://user-images.githubusercontent.com/7539871/234491556-04263308-3f2f-4fa4-9293-3c0bb7ad5112.png">

For the "LOL" object, all of the custom properties do show in the data store, including the ones that shouldn't (like alpha and scale).


Do you think there's an issue with my code, or perhaps there's a bug?

Thank you

Edit: i should add, I'm issuing the regular release of 3.60

**Comment by samme** [comment] 2023-04-26 19:31
> For the "LOL" object, all of the custom properties do show in the data store, including the ones that shouldn't (like alpha and scale).

This is definitely in Phaser v3.60.0, not a beta? I can't think of why that would happen. In [tilemap/create from objects](https://labs.phaser.io/edit.html?src=src/tilemap/create%20from%20objects.js) `alpha` is working correctly (see dim coin at top).

**Comment by paxperscientiam** [comment] 2023-04-26 23:00
I just scrutinized "node_modules/phaser/package.json" and can confirm that package.json.version indicates as much.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/7539871/234720539-eeef4606-47a5-4149-8922-dbd38445df59.png">

I will try again from scratch with what you shared.

**Comment by photonstorm** [comment] 2023-04-27 00:08
> I just scrutinized "node_modules/phaser/package.json" and can confirm that package.json.version indicates as much.

Check the browser Dev Tools. Phaser logs its version number to the console when it boots. For example, you may have npm at 3.60 but override it with a different package / script tag. Worth checking.

**Comment by paxperscientiam** [comment] 2023-04-27 01:41
Indicated there too, I'm afraid.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7539871/234738395-7a645cc5-52eb-4015-a6ce-1ea9828d3a05.png">

To clarify, I'm using vite as my build tool; only mentioning it because the only hard coded script tag in my project is that which points to vite's bundle.

I'll try to see if I can replicate what I'm experiencing with a minimal setup.

**Comment by paxperscientiam** [comment] 2023-04-28 06:36
Hmm, I'm still getting unexpected results.

Tiled object:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/7539871/235072160-7b85d94b-0973-4532-8b22-de890cd2ae7a.png">

<img width="252" alt="image" src="https://user-images.githubusercontent.com/7539871/235072228-845a04fe-0b3a-4583-b21a-5ace796397c7.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/7539871/235072319-ba1d8682-45ab-4f37-ae59-47fa41e51ab5.png">

I created a gist that will hopefully help anyone else reproduce what I'm seeing. 🤞

https://gist.github.com/paxperscientiam/c6a443d5315f2ce7b7e843c40353e073

**Comment by samme** [comment] 2023-04-28 15:42
@paxperscientiam I reproduced your problem. @photonstorm could you reopen?

**Comment by paxperscientiam** [comment] 2023-04-29 17:42
Thanks @samme
