### ISSUE TITLE
Tilesprite width / height not respected one dimension is zero

### ISSUE THREAD

**Issue by GaryStanton** [phaserjs/phaser#6857] opened 2024-07-08 15:25 UTC
## Version
* Phaser Version: 3.80.0
* Operating system: Windows 10
* Browser: all

## Description
If you set a tilesprite with a zero width or height, and specify the other dimension - while it does take the dimensions from the texture, as it should, it doesn't tile the sprite to the other dimension. 

So for example, if I have a texture that is 100x100px, I would expect the following code to result in a tile sprite that is 100px wide and 500px high, with my texture tiled five times vertically:
`this.add.tileSprite(0, 0, 0, 500, 'my100pxTexture')`

However, it simply results in a tilesprite of 100x100px, matching the dimensions of the texture.

## Example Test Code

https://phaser.io/sandbox/4nryhSBH

**Comment by zekeatchan** [comment] 2024-07-10 09:17
Hi @GaryStanton. Thanks for submitting this issue. We have fixed this and pushed it to the `master` branch. It will be part of the next release. Do test it out and let us know if you encounter any issues.

**Closed as completed by zekeatchan** 2024-07-10 09:17 UTC

**Comment by codingthat** [comment] 2024-11-15 16:22
@zekeatchan this appears to be a regression in 4.0.0-beta.1.  You can verify this easily thanks to @GaryStanton 's [sandbox MRE](https://phaser.io/sandbox/4nryhSBH).

**Comment by BenjaminDRichards** [comment] 2024-11-18 22:20
@codingthat I cannot replicate, but that just means my device isn't affected by the issue. Can you describe the system (browser, version, operating system) where the problem occurs? This will help us identify possible issues.

**Comment by GaryStanton** [comment] 2024-11-18 22:44
@BenjaminDRichards I can replicate this in Chrome and Firefox. There's a simple test case at https://phaser.io/sandbox/4nryhSBH, and if you switch between 3.87.0 and 4.0.0 Beta 1, you can see the difference.

![image](https://github.com/user-attachments/assets/602ac518-6da2-45cf-9c6e-318ac5dfbaf7)

![image](https://github.com/user-attachments/assets/a21d7c57-b5b7-4dae-8ee7-7a6346525ee7)

**Comment by BenjaminDRichards** [comment] 2024-11-18 22:51
Aha, I see what's going on. Thanks for illustrating it!

TileSprite checks for valid width and height when it's created. In the 4.0.0-beta1 code, the check fails if _either_ dimension. It falls back to using the frame dimensions, i.e. the size of one sprite.

It seems more logical to check each dimension independently, so that here the intended height is preserved. I'll implement that now; it should be in beta2 very soon.
