### ISSUE TITLE
Pixel distortion / shifting when using setDepth()

### ISSUE THREAD

**Issue by rb1147x** [phaserjs/phaser#6692] opened 2023-12-11 16:13 UTC
## Version

* Phaser Version: 3.70.0

* Operating system: Windows 11

* Browser: Observed in both Chrome 121.0.6167.8 and Firefox 120.0.1

## Description

Game objects appear to visually shift slightly when interacted with, which appears to be based on ```setDepth()```. Although, this may not actually be the culprit. Here's an example:

![pixelshifting](https://github.com/photonstorm/phaser/assets/17628197/67611fea-76f2-4814-8915-d6b90a0bb624)

Which you can interact with here: https://jsitor.com/3vkO_hzB0S

I had made a forum post about this: https://phaser.discourse.group/t/pixel-distortion-shifting-issue/13774 so the full context is available there, but after commenting out ```setDepth()```, which is being used to bring the object to the front so that it can be dragged over other game objects, the problem goes away.

On the forum post, there was a solution posted to specifically set ```roundPixels``` to ```false``` on the camera, which does solve this problem. However, this seems like a bug? Why would setting a game object's depth cause this visual issue? Also, this problem does not happen in 3.60.0.

Thanks.

## Example Test Code

https://jsitor.com/3vkO_hzB0S

**Comment by KingCosmic** [comment] 2023-12-15 18:10
Looks like it's only a issue with the WEBGL renderer, can't get it to reproduce in canvas.

**Comment by KingCosmic** [comment] 2023-12-15 18:35
seems to only be an issue in WEBGL and not CANVAS, also seems to be an issue with having multiple scenes render, I consolidated your example test code into a single scene (with some minor adjustments) https://jsitor.com/z3lB4A5yWE and can't get it to reproduce afterwards. I'm not versed enough in the webgl renderer to dive much further but hopefully this helps Richard or someone else track this down.

**Comment by rb1147x** [comment] 2023-12-15 19:00
Thanks for taking a look. My original example was born from the project I'm working on that uses two scenes - one for the game world and one for drawing UI objects and handling UI interactions (e.g. dragging game items to your inventory). Although the issue presented itself while using ```setDepth()``` and there's at least a temporary fix by setting the UI scene's camera ```roundPixels``` property to false, maybe the root issue is more in line with what you've discovered - using webGL and multiple scenes.

**Comment by samme** [comment] 2024-04-30 02:28
I reproduced this with 1 Graphics, 1 Image, and `moveUp()`: https://phaser.io/sandbox/q89fEzzs

**Comment by photonstorm** [comment] 2024-09-02 21:06
Thanks for that example @samme - this was a roundPixels issue and is fixed in v3.85 - you can confirm this in the sandbox by changing the version to 'dev'.

**Closed as completed by photonstorm** 2024-09-02 21:06 UTC
Labels: 🔮 Renderer (WebGL)
