### ISSUE TITLE
Pushable `false` bodies still move when circle shaped

### ISSUE THREAD

**Issue by kainage** [phaserjs/phaser#5617] opened 2021-03-24 03:18 UTC
## Version

* Phaser Version: 3.53.1
* Operating system: Mac, Linux

## Description

Bodies are still pushable when both `pushable` values are set to `false` when either one of them is a circle. 
Works fine only when both are rectangles.

## Example Test Code

```js
var config = {
    type: Phaser.AUTO,
    width: 864,
    height: 632,
    parent: 'phaser-example',
    backgroundColor: '#2d2d2d',
    physics: {
        default: 'arcade',
        arcade: {
            gravity: { y: 0 },
            debug: true
        }
    },
    scene: {
        preload: preload,
        create: create,
        update: update,
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.setPath('assets/sprites');
    this.load.image('blockANP');
    this.load.image('blockBNP');
}

var cursors
var left

function create ()
{
    this.physics.world.setBounds(0, 0, 864, 632);

    cursors = this.input.keyboard.createCursorKeys();

    left = this.physics.add.image(200, 196-16, 'blockANP').setCollideWorldBounds().setInteractive();
    var right = this.physics.add.image(600, 196-16, 'blockBNP').setCollideWorldBounds().setInteractive();

    left.setBounce(0.5);
    right.setBounce(0.5);

    // If either one of these are a circle they will get pushed.
 
    left.setCircle(32)
    right.setCircle(32)

    left.setPushable(false);
    right.setPushable(false);

    this.physics.add.collider(left, right);
}

function update ()
{
    if (cursors.left.isDown)
    {
        left.setVelocityX(-160);
    }
    else if (cursors.right.isDown)
    {
        left.setVelocityX(160);
    }
    else if (cursors.up.isDown)
    {
        left.setVelocityY(-160);
    }
    else if (cursors.down.isDown)
    {
        left.setVelocityY(160);
    }
    else {
        left.setVelocity(0)
    }
}
```

**Comment by dartinger** [comment] 2022-02-25 22:22
I can confirm the problem wasn't solved until version 3.55.2. (OS: Linux/Ubuntu)

**Comment by pixel-fabian** [comment] 2022-02-28 20:59
I am also struggling with this issue.

**Comment by SlimHajRomdhane** [comment] 2023-03-25 11:04
To fix this issue, you can set the pushable property on the circle body as well as on the image. Add the following lines of code after setting the circle radius for each image:

left.body.setCircle(32, 0, 0);
left.body.pushable = false;

right.body.setCircle(32, 0, 0);
right.body.pushable = false;

This sets the pushable property of both the image and the circle body to false, ensuring that they cannot be pushed.
I hope this helps!
- SlimHR

**Comment by zekeatchan** [comment] 2024-06-18 02:54
This issue has been resolved.

Arcade body circles `setPushable` method updated to include collisions between two circles. Setting the Arcade Body setPushable(false) method for circle bodies prevents them from being pushed by other circle bodies.

This will be included in the next update. Thank you for bringing this to our attention!

**Closed by zekeatchan** 2024-06-18 02:54 UTC
Labels: 🧱 Physics
