### ISSUE TITLE
BitmapMask scaling incorrectly when game size is set manually

### ISSUE THREAD

**Issue by crockergd** [phaserjs/phaser#6531] opened 2023-06-21 19:31 UTC
## Version

* Phaser Version: 3.60.beta-19+

* Operating system: Windows + Android

* Browser:

## Description

Applying a BitmapMask in a game that uses the FIT scale mode and sets game size manually (to handle DPR scaling on mobile) no longer works correctly as of 3.60.0-beta.19. Any texture that a BitmapMask is applied to appears to scale and transform based on the manually set game size (game size * DPR) and not the final game size the FIT scaling mode enforces to stay within the window.

## Example Test Code

https://codepen.io/crockergd/pen/abQmyvL

Functioning correctly, the demo should display a large grey square in the middle of the canvas being masked by a red stripe through the middle. This can be seen by setting the Phaser dependency to https://cdn.jsdelivr.net/npm/phaser@3.60.0-beta.18/dist/phaser.min.js or earlier. Using any dependency of 3.60.0-beta.19 or later causes the grey square to scale and transform as if the canvas was larger, but the mask texture to remain in the correct spot and still mask off parts of the grey square as if it was correctly placed.

## Additional Information

I've set the game size scaling in the demo to be 1.5, but this affects any scaling above 1.

Rescaling textures or masks to account for this new behaviour cannot resolve the issue, it's challenging to demonstrate in a codepen but the cropping functionality of the mask (the section clipped out) cannot be scaled in any way I can find. This makes masks of complex shapes no longer viable. Neither scaling the original texture used to create the mask, nor the masked texture itself seems to affect this.

**Comment by neki-dev** [comment] 2023-07-04 18:32
I have same problem, but on sprites with shaders.
For example: https://www.veed.io/view/c5e8269f-785e-46c1-8c05-a62eba83aeed?panel=share
On resize screen - sprite without shader scaling normal, but with shader i get incorrect scaling.

**Comment by photonstorm** [comment] 2023-07-21 16:37
Thanks for opening this, but it's a duplicate of #6527 (which itself is sort of a duplicate of #6503) so am tagging them here for completeness, but closing this as it needs tracking in the older issue.

**Closed as completed by photonstorm** 2023-07-21 16:37 UTC
